name: Auto Documentação QVS

on:
  push:
    paths:
      - '**/*.qvs'  # dispara só quando arquivos .qvs mudarem
  workflow_dispatch:  # permite rodar manualmente

jobs:
  gerar-documentacao:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install openai

      - name: Executar script de atualização de documentação
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python update_docs.py

      - name: Commit e Push alterações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Atualização automática de documentação QVS [$(date +'%d/%m/%Y %H:%M:%S')]"
          git push
        continue-on-error: true
